### ISSUE TITLE
State is not being changed on playlist save

### ISSUE THREAD

**Issue by farishkash** [yummymell0w/jammming#5]
Step 95.  Suppose to change playlist name to New Playlist and reset the default playlisttracks to an empty array on save.

**Comment by yummymell0w** [comment]
So I reset the state of playlistName and searchResults. Also I decided to reset the state of playlistTracks.
I tested that everything is reset when clicking Save playlist button except playlistName. I know that the value of playlistName has changed but React does not rerender it. any ideas?
savePlaylist() {
        let trackURIs = this.state.playlistTracks.map(track => {
            return track.uri;
        });
        Spotify.savePlaylist(this.state.playlistName, trackURIs);
        this.setState({
            playlistName: 'New playlist'
        });
        this.setState({
            playlistTracks: []
        });
        this.setState({
            searchResults: []
        });
    }

**Comment by farishkash** [comment]
You only call setState once.  Include it in a then statement as a promise so after the playlist has been saved you can set the state.

```
Spotify.savePlaylist(this.state.playlistName, trackURIs).then(() => {
this.setState({
playlistName: 'New playlist',
playlistTracks: [],
searchResults: []
});
});
```

**Comment by yummymell0w** [comment]
thanks for advice!
