### ISSUE TITLE
Add and remove track functions.

### ISSUE THREAD

**Issue by farishkash** [yummymell0w/jammming#6]
```
addTrack(track) {
        let array = this.state.playlistTracks.slice();
        let index = array.indexOf(track);
        if (index >= 0) {
            return;
        }

        array.push(track);
        this.setState({playlistTracks: array});
    }

    removeTrack(track) {
        let array = this.state.playlistTracks.slice();
        let index = array.indexOf(track);
        array.splice(index, 1);
        this.setState({playlistTracks: array});
    }
```
This seems to have some extra and unneeded code.

For example for addTrack this works, no need to slice.  You are just adding to the array and then setting that array to the playlistTracks.  This is more an efficiency issue since your code works.

```
addTrack(track) {
        let array = this.state.playlistTracks
        array.push(track);
        this.setState({playlistTracks: array});
    }
```

**Comment by yummymell0w** [comment]
In addTrack and removeTrack methods I used slice method because I read that it is not recommended to perform operations directly on the properties of the state object.
Also my code checks if the track already exists in the playlist and does not allow to add the same track twice.

**Comment by farishkash** [comment]
That is true and is a principal of redux.

Here is the thing, when you use 

addTrack(track) {
        let array = this.state.playlistTracks
        array.push(track);
        this.setState({playlistTracks: array});
    }
You aren't performing an operation directly on state either, you are just setting a new one.


Second 
Also if you truly want to check if the item doesn't exist, you need to compare the id of the track with the ids of the tracks on the playlist.  I don't see that function present.  

All you are doing is manipulating that element based on the location index.  What if you hand something else on that index?  

Just more items to consider here.
