### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [yummymell0w/jammming#7]
Met expectations.

Everything is working great when testing the app.  I extracted your client id from the dist folder and put it into the build folder so I can run it locally.

I really didn't see any major issues.  Your addTrack and removeTrack method I pointed out because I hadn't see this approach on this project before and truth be told it really isn't necessary.

One big caveat, you should never include api keys such as client id in dist folders.  They should be treated as an environmental variable in your code.  If you already know this, sorry for the reminder.

**Comment by yummymell0w** [comment]
Thanks for reviewing my project.
I forgot to remove my key from dist folder. Good reminder!
